# Generated by Django 5.0.1 on 2024-02-13 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('instockqty', models.IntegerField()),
                ('costprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdealer', models.CharField(max_length=40)),
                ('contactperson', models.CharField(max_length=40)),
                ('nameofparticular', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField()),
                ('phoneno', models.IntegerField()),
                ('date', models.DateField(max_length=40)),
                ('status', models.CharField(choices=[('DONE', 'done'), ('PENDING', 'pending')], default='DONE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=40)),
                ('profit', models.IntegerField()),
                ('totalsoldout', models.IntegerField()),
                ('item_qty_price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.items')),
                ('order_qty_price', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofproduct', models.CharField(max_length=40)),
                ('buyedfromdealer', models.IntegerField()),
                ('dateofpurchased', models.DateField(max_length=40)),
                ('problemdetail', models.CharField(max_length=100)),
                ('customerdetail', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
